import { useRouter } from 'next/dist/client/router'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react'
import { useAppSelector } from '../app/hooks'
import styles from '../styles/Home.module.css'

export default function Home() {

  const userState = useAppSelector((state) => state.user);
  const router = useRouter();

  useEffect(() => {
    if(userState && userState.user && userState.user._id) {
      router.push("/usertask");
    } else {
      router.push("/login")
    }
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}></main>

      <footer className={styles.footer}></footer>
    </div>
  )
}
